### ISSUE TITLE
Please update copyright notices

### ISSUE THREAD

**Issue by smcv** [lathiat/nss-mdns#61]
While updating Debian's nss-mdns package I noticed that the most recent copyright notices in this project say it is © 2004-2007 Lennart Poettering. Presumably the new maintainers have written something copyrightable since then?

(I can guess at authors from the git history, but I can't know who holds the copyright: for example @agoode's contributions might be © Adam Goode, © Google Inc., or a mixture of the two.)

**Comment by agoode** [comment]
For my contributions, I have to follow the guidelines at
https://opensource.google.com/docs/patching/ and https://opensource.google.com/docs/copyright/

For nss-mdns, this meant updating https://github.com/lathiat/nss-mdns/blob/master/ACKNOWLEDGEMENTS.md, but otherwise leaving all the copyright lines completely alone.

(I see now that I didn't quite get the authors file correct for the current guidelines, so I will have to fix that.)

**Comment by agoode** [comment]
I'm not going to do this given the recommendation not to change the existing copyright notices for any reason.

git blame or git log should be used to determine authorship at a fine-grained level.
